version: '{build}'
environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
#

build_script:
  - gradlew buildPlugin --info
#

artifacts:
  - path: 'build\distributions\*.zip'
    name: window-layout-manager
#

deploy_script:
- ps: >-
    if($env:appveyor_repo_branch -eq 'master') {
      .\gradlew publishPlugin
    }
#