version: '{build}'
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew build --build-cache --parallel -PwarningsAsErrors=true
#

artifacts:
  - path: 'build\distributions\*.zip'
    name: window-layout-manager
#